### ISSUE TITLE
Name Text - Shadow (option inverted)

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/NotPlater#4]
Not a big bug.

Just the tick box for Enable Shadow does the opposite of what you'd expect. 
Enable Shadow -> Hides the shadow.
Disabling Shadow -> Shows the shadow.

![image](https://user-images.githubusercontent.com/72258441/224915164-f434e8a2-b38d-48fb-97d1-edcb5dbcb55a.png)
![image](https://user-images.githubusercontent.com/72258441/224915192-50686b73-073d-4572-860b-275bf11f30e2.png)

**Edit:** 
Actually, after playing with it, it seems both options have the shadow enabled. The image above just has the offset at 0,0. So it appears to not be there since it's directly under the font.

Disable Shadow seems to keep the shadow enabled, but gives it a preset offset or something.

**Comment by RichSteini** [comment]
This is actually functioning as intended. When you disable the shadow option then it restores the default shadow of the text. You can still have no shadow by enabling it and keeping the shadow offset at 0. Should maybe give a hint or rename the option, but in general it is not a bug.
