### ISSUE TITLE
Level Text Position (not saving)

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/NotPlater#5]
Altering level position isn't saved. Hiding the name plates, then showing them again. Reloading, or just turning around so they're not in the screen and turning back will revert the y position of the level text.

https://user-images.githubusercontent.com/72258441/224923855-562f3d08-8392-464e-b2de-2b0644e5a375.mp4

**Comment by RichSteini** [comment]
I cannot reproduce this. Try to disable other addons, delete saved variables and make sure you got the latest version.

**Comment by Foodlenz** [comment]
I think it's the Anchor that's causing the issue. 
**Works fine:** Bottomleft, Bottomright, Left, Top, Topleft, Topright
**Broken as above:** Bottom, Center, Right, 

Tested it with all my stuff loaded and tested again with only compatibility. Same thing both times.
