### ISSUE TITLE
[Healthbar] HP Bar doesnt Update after first hit on Target

### ISSUE THREAD

**Issue by Wathsup** [RichSteini/NotPlater#7]
Problem:
After the target takes the first damage from an ability or auto attack, the Healthbar does not update any further.

Reference:
https://streamable.com/akrxwn

**Comment by RichSteini** [comment]
I am pretty sure that the reference you linked here is not NotPlater addon, i tried it but cannot replicate your issues. Do you have multiple nameplate addons installed?  The nameplates in the video look like the ones that come with elvui or something like that.

**Comment by Wathsup** [comment]
Oh my god yes, the Elvui Nameplates reactivated themselves after the update. My bad LOL
