### ISSUE TITLE
Stacking Error

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/NotPlater#9]
Hey,

Getting the following errors pop up after clicking the Stacking option.

> Message: Interface\AddOns\NotPlater\modules\stacking.lua:32: attempt to index field 'size' (a nil value)
Time: 05/19/23 21:31:13
Count: 1
Stack: (tail call): ?
Interface\AddOns\NotPlater\modules\stacking.lua:32: in function `StackingCheck'
Interface\AddOns\NotPlater\modules\stacking.lua:22: in function `ConfigureStacking'
Interface\AddOns\NotPlater\NotPlater.lua:99: in function `PrepareFrame'
Interface\AddOns\NotPlater\misc\simulatorFrame.lua:394: in function `ConstructSimulatorFrame'
Interface\AddOns\NotPlater\misc\simulatorFrame.lua:266: in function `ShowSimulatorFrame'
Interface\AddOns\NotPlater\misc\simulatorFrame.lua:261: in function `ToggleSimulatorFrame'
Interface\AddOns\NotPlater\misc\configPrototypes.lua:704: in function <Interface\AddOns\NotPlater\misc\configPrototypes.lua:704>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:818: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
...face\AddOns\WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:318: in function `Fire'
...uras\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:22: in function <...uras\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

and...

> Message: Interface\AddOns\NotPlater\misc\simulatorFrame.lua:213: <unnamed>:SetText(): Font not set
Time: 05/19/23 21:31:21
Count: 1661
Stack: [C]: ?
[C]: in function `SetText'
Interface\AddOns\NotPlater\misc\simulatorFrame.lua:213: in function <Interface\AddOns\NotPlater\misc\simulatorFrame.lua:206>

and....

> Message: Interface\AddOns\NotPlater\modules\stacking.lua:16: Usage: <unnamed>:SetFrameStrata(level)
Time: 05/19/23 21:35:04
Count: 2967
Stack: [C]: ?
[C]: in function `SetFrameStrata'
Interface\AddOns\NotPlater\modules\stacking.lua:16: in function `SetNormalFrameStrata'
Interface\AddOns\NotPlater\modules\target.lua:200: in function `TargetCheck'
Interface\AddOns\NotPlater\NotPlater.lua:78: in function <Interface\AddOns\NotPlater\NotPlater.lua:73>
...e\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:92: in function <...e\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:87>

**Comment by RichSteini** [comment]
Thanks for the reports. Fixed in [Fix stacking error](https://github.com/RichSteini/NotPlater/commit/11381dcfb689b30fb1382b1962a04c29a2a9b380). You might notice that the simulated frame moves within the simulator frame when activating this option. This is the normal centered behaviour, because the clickable frame of the nameplate gets resized to the same size as the healthbar when activating the stacking option. The clickable frame is the actual nameplate, the parent of healthbar and castbar.
